### ISSUE TITLE
Error on first execution

### ISSUE THREAD

**Issue by flaschbier** [flaschbier/sound-machine-electron#1]
```
Uncaught Exception:
TypeError: mainWindow.loadUrl is not a function
    at App.<anonymous> (/Users/***/workspace/Electron/sound-machine-electron/main.js:13:16)
    at App.emit (events.js:205:15)
```

**Comment by flaschbier** [comment]
instead `loadFile`:

```javascript
//    mainWindow.loadUrl('file://' + __dirname + '/app/index.html');
    mainWindow.loadFile('app/index.html');
```

 cf. https://electronjs.org/docs/api/browser-window#winloadfilefilepath-options
