### ISSUE TITLE
close button implementation: no module ipc

### ISSUE THREAD

**Issue by flaschbier** [flaschbier/sound-machine-electron#3]
```
$ npm start

> sound_machine@0.1.0 start /Users/***/workspace/Electron/sound-machine-electron
> electron .

App threw an error during load
Error: Cannot find module 'ipc'
```

**Comment by flaschbier** [comment]
IPC implementation has changed, cf. https://electronjs.org/docs/api/ipc-main

Replacing the `require`s accordingly.
But:

```
Uncaught ReferenceError: require is not defined
    at index.js:2
```

**Comment by flaschbier** [comment]
cf. https://stackoverflow.com/questions/55093700/electron-5-0-0-uncaught-referenceerror-require-is-not-defined added

```javascript
    mainWindow = new BrowserWindow({
        ...
        webPreferences: {
            nodeIntegration: true
        }
    });
```

but now on click of close button:

```
Uncaught Exception:
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'WebContents'
    --- property 'webContents' closes the circle
    at JSON.stringify (<anonymous>)
    at EventEmitter.<anonymous> (/Users/****/workspace/Electron/sound-machine-electron/main.js:24:31)
    at EventEmitter.emit (events.js:200:13)
    at WebContents.<anonymous> (/Users/****/workspace/Electron/sound-machine-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:335:21)
    at WebContents.emit (events.js:200:13)
```

**Comment by flaschbier** [comment]
ok, the latter was the attempt to `console.out` a `JSON.stringify` of the event...

Remarks:
- `console.out` in renderer goes to browser console (in Developer Tools)
- `console.out` in main goes to shell window

fixing the code to not use `JSON.stringify` before committing.
