### ISSUE TITLE
Cannot find module 'global-shortcut'

### ISSUE THREAD

**Issue by flaschbier** [flaschbier/sound-machine-electron#5]
After adding

```javascript
var globalShortcut = require('global-shortcut');
```

to `main.js`, the following error is thrown:

```
$ npm start

> sound_machine@0.1.0 start /Users/****/workspace/Electron/sound-machine-electron
> electron .

App threw an error during load
Error: Cannot find module 'global-shortcut'
Require stack:
- /Users/****/workspace/Electron/sound-machine-electron/main.js
- /Users/****/workspace/Electron/sound-machine-electron/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:627:15)
    at Function.Module._resolveFilename (/Users/****/workspace/Electron/sound-machine-electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:41:16)
    at Function.Module._load (internal/modules/cjs/loader.js:531:27)
    at Module.require (internal/modules/cjs/loader.js:685:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/Users/****/workspace/Electron/sound-machine-electron/main.js:5:22)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
```

**Comment by flaschbier** [comment]
Also `global-shortcut` is now exposed via `electron`:

```javascript
const {app, BrowserWindow, ipcMain, globalShortcut} = require('electron');
```

cf. https://electronjs.org/docs/api/global-shortcut
